# Generated by Django 3.1.7 on 2021-03-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_secs', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_secs', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('participants', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_in_secs', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
        ),
    ]
